### ISSUE TITLE
LPC booting into ISP mode after quick power reset

### ISSUE THREAD

**Issue by henrique-silva** [lnls-dig/rffe-uc-hw#14]
After a quick power-off/power-on the controller boots in ISP mode, waiting for new programming commands, not booting the application firmware.
This can be a problem since this hardware is not connected on a no-break in production environment.
The problem most likely is in the RTS/DTR logic circuitry, probably an unknown initial state.

**Comment by augustofg** [comment]
The DTR and RTS pins are floating when the CP2102 isn't powered (USB disconnected). This causes the RTS and DTR lines to build charge and go to HIGH.

Due the 1uF capacitor in the LPC_RESET line the microcontroller will reset after USB_RTS is already HIGH (forcing P2.10 to low) and the ROM bootloader will enter ISP and watch UART0 for commands.

This also happens when the RFFE uC board is cold enough (I tested this with a freeze spray and could get repeatable results).

Ensuing a remote reset command through the TCP would also make the board reset and enter bootloader ISP sometimes with the newer firmware before https://github.com/lnls-dig/rffe-uc-fw/commit/e7ffb1afbac407f47f27d8d67d6db6e563afe9d5 .

The older firmware didn't exhibited this behavior becaused it used the watchdog to cause a reset, but it never cleared the WDTOF flag. An interesting side effect resulting from this was that the bootloader would never enter in ISP mode again until the RFFE suffered a power cycle (check the LPC176x/5x User Manual rev 4.1, chapter 32 Boot process flowchart, page 630). While WDTOF was set, lpc21isp wouldn't be able to force the microcontroller into ISP mode.

The last release of the new firmware sets the WDTOF flag before resetting the microcontroller through the SYSRESETREQ flag in the [AICR register](http://infocenter.arm.com/help/index.jsp?topic=/com.arm.doc.dui0552a/Cihehdge.html) and immediately clears WDTOF after resetting. In that way the software reset never enters ISP mode, but lpc21isp still can put the microcontroller in ISP mode.

Anyway, the fix is simple. Soldering two 1k pull-down resistors in the USB_DTR and USB_RTS lines fix the problem.
