### ISSUE TITLE
Serial communication resets LPC1769

### ISSUE THREAD

**Issue by aylons** [lnls-dig/rffe-uc-hw#5]
Due to the way the software drives the USB IC DTR, the IC does not work in serial mode because USB DTR keeps reseting the chip. Another connection between IC2 and IC5 should be devised for that.

**Comment by henrique-silva** [comment]
This problem happens because the USB-to-Serial converter is configured to assert the DTR and RTS lines when a communication port is open by the host's driver. If the DTR line is connected directly to the Reset pin, it  will keep the reset signal asserted as long as the serial port is open.

Since we're using the [lpc21isp](https://github.com/domenpk/lpc21isp) software to program the LPC using the serial port, we're able to change the code a little and control the RTS and DTR lines independently. These changes will be committed to a new fork in the lnls-dig repository.
This customization is needed because the LPC1768 needs to have P2.10 pin set to ground after reset in order to enter ISP programming mode.

The connection logic should be:

- LPC Reset = [DTR] XNOR [RTS]
- P2.10 = NOT [RTS]

LPC1768 pins are 5V tolerant, so we can use standard TTL logic.

The meaning of each USB line (DTR and RTS) combination will be explained on the programmer software commit.
